language: python
python:
  - "3.5.2"
 
os: "ubuntu"
# whitelist

  
install:
- sudo apt-get update
- git clone https://github.com/yutiansut/quantaxis
- cd quantaxis
- git checkout 0.3.9
- pip install .
# command to build

script: 
- quantaxis
