language: python
python:
  - "3.6"
 

# whitelist
branches:
  only:
    - 0.3.9-beta
 
# Use this to prepare the system to install prerequisites or dependencies
before_install: "pip install  -r requirements.txt "
 
# command to install dependencies
install: "python setup.py install"
 
# command to build
script: python -m QUANTAXIS
 
after_success:
    "examples"