
language: python
python:
  - "3.6.1"
  - "3.5.0"
  - "3.4.0"
  - "3.3.0"
  - "3.2.0"
 
os: "ubuntu"
# whitelist

 
# Use this to prepare the system to install prerequisites or dependencies


# command to install dependencies
install: 
- "sudo apt-get update"
- "sudo apt-get install python3-dev"
- "pip install -r requirements.txt"
- "pip install tushare"
# command to build
script: "python setup.py install"
 
#after_success:
    #"python easy_start_tushare.py"
