environment:
  matrix:
  - PYTHON: C:\Python33\python.exe
    platform: Any CPU
  - PYTHON: C:\Python34\python.exe
    platform: Any CPU
  - PYTHON: C:\Python35\python.exe
    platform: Any CPU
  - PYTHON: C:\Python36\python.exe
    platform: Any CPU
before_build:
  - "%PYTHON% -m pip install virtualenv"
  - "%PYTHON% -m virtualenv venv"

  - "%PYTHON% -m pip install requirements.txt"


build_script:
  - pip install -U pip
  - python setup.py develop

before_test:

  - pip install requirements.txt

test_script:
  - "%PYTHON% setup.py install"

#on_success:
#  - coveralls